
live_config_reload = true

[env]
TERM = "xterm-256color"

# [shell]
# program = "/bin/zsh"
# args = [ "-l", "-c", "tmux attach-session -t" ]

[window]
dynamic_padding = false
decorations = "buttonless"
startup_mode = "Fullscreen"

  [window.padding]
  x = 10
  y = 12

[font]
size = 13

# normal = { family = "BlexMono Nerd Font Mono", style = "Bold" }
# italic = { family = "BlexMono Nerd Font Mono", style = "Bold Italic" }
# bold_italic = { family = "BlexMono Nerd Font Mono", style = "Bold Italic" }

  # [font.normal]
  # family = "JetBrainsMono Nerd Font"
  # style = "Bold"
  #
  # [font.italic]
  # family = "JetBrainsMono Nerd Font Mono"
  # style = "Bold Italic"
  #
  # [font.bold_italic]
  # family = "JetBrainsMono Nerd Font Mono"
  # style = "Bold Italic"

 normal = { family = "MonoLisaNerdFontCompleteMono Nerd Font", style = "Regular" }
 italic = { family = "MonoLisaNerdFontCompleteMono Nerd Font", style = "Italic" }
 bold_italic = { family = "MonoLisaNerdFontCompleteMono Nerd Font", style = "Bold Italic" }

 # normal = { family = "Liga SFMono Nerd Font", style = "Bold" }
 # italic = { family = "Liga SFMono Nerd Font", style = "Bold Italic" }
 # bold_italic = { family = "Liga SFMono Nerd Font", style = "Bold Italic" }

  # [font.normal]
  # family = "Liga SFMono Nerd Font"
  # style = "Bold"
  #
  # [font.italic]
  # family = "Liga SFMono Nerd Font"
  # style = "Bold Italic"
  #
  # [font.bold_italic]
  # family = "Liga SFMono Nerd Font"
  # style = "Bold Italic"

  # [font.normal]
  # family = "BlexMono Nerd Font Mono"
  # style = "Bold"
  #
  # [font.italic]
  # family = "BlexMono Nerd Font Mono"
  # style = "Bold Italic"
  #
  # [font.bold_italic]
  # family = "BlexMono Nerd Font Mono"
  # style = "Bold Italic"

  # [font.normal]
  # family = "Mononoki Nerd Font"
  # style = "Bold"
  #
  # [font.italic]
  # family = "Mononoki Nerd Font"
  # style = "Bold Italic"
  #
  # [font.bold_italic]
  # family = "Mononoki Nerd Font"
  # style = "Bold Italic"

[colors]
  [colors.primary]
  background = "0x1a1b26"
  foreground = "0xc0caf5"

  [colors.normal]
  black = "0x15161E"
  red = "0xf7768e"
  green = "0x9ece6a"
  yellow = "0xe0af68"
  blue = "0x7aa2f7"
  magenta = "0xbb9af7"
  cyan = "0x7dcfff"
  white = "0xa9b1d6"

  [colors.bright]
  black = "0x414868"
  red = "0xf7768e"
  green = "0x9ece6a"
  yellow = "0xe0af68"
  blue = "0x7aa2f7"
  magenta = "0xbb9af7"
  cyan = "0x7dcfff"
  white = "0xc0caf5"

  [[colors.indexed_colors]]
  index = 16
  color = "0xff9e64"

  [[colors.indexed_colors]]
  index = 17
  color = "0xdb4b4b"

[selection]
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>"
save_to_clipboard = false
